### ISSUE TITLE
DB 연결 기능 추가

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv-admin#18]
**Task 설명**
DB(postgreSQL)에 연결하는 기능을 추가합니다.

**TODO**

- [x] DB 연결 기능 추가
- [x] 로컬 DB 연결 테스트
- [x] 테스트 DB 연결 테스트
- [x] 개발 서버 DB 연결 테스트

**레퍼런스**
- https://blog.dork94.com/194

**추가적인 설명**
개발 서버 DB 연결 테스트는 제가 진행합니다. env의 경우는 구글 드라이브에 올려주세요.
